server {
   listen    9090;
   client_max_body_size 1024m;

   location / {
        proxy_pass http://127.0.0.1:9000;  # 容器 IP 和服务端口
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 30s;  # 连接超时
        proxy_send_timeout 60s;     # 发送超时
        proxy_read_timeout 60s;     # 读取超时
    }
}